export default {
  id: 999,
  default: 0,
  name: '',
  zipcode: '1',
  address: '1',
  number: '1',
  city: '1',
  state: '1',
  district: '1',
  destination_name: 'fake',
  destination_last_name: 'fake',
  country: 'fake',
  complement: null,
  client_id: null,
};
